---
jira_tickets_info_task:
  description: >
    Use the JIRA Ticket Fetcher tool to fetch and summarize details for the given Jira ticket IDs: {ticket_ids}.
    For each ticket, include the summary, description, status, and recent comments.
  expected_output: >
    A JSON list containing detailed information for each Jira ticket with fields: id, summary, description, status, and comments.
  agent: jira_specialist

review_jira_impact_task:
  description: >
    Review the Jira ticket information provided by the previous task and assess its impact on RBI.
    Analyze the technical and business implications of each ticket.
  expected_output: >
    A detailed analysis report in MARKDOWN format with:
    - Affected components of RBI
    - Current code references if applicable
    - Highlighted risks, dependencies, or required actions
    - Recommendations for implementation
  agent: reviewer_agent